In [135]:
import numpy as np
import pandas as pd

In [136]:
books = pd.read_csv("Books.csv")
users = pd.read_csv("users.csv")
ratings = pd.read_csv("ratings.csv")

C:\Users\NutanTripathy\AppData\Local\Temp\ipykernel_3528\3358372675.py:1: DtypeWarning: Columns (3) have mixed types. Specify dtype option on import or set low_memory=False.
  books = pd.read_csv("Books.csv")

In [137]:
books.head()

,ISBN,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
0,0195153448,Classical Mythology,Mark P. O. Morford,2002,Oxford University Press,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...
1,0002005018,Clara Callan,Richard Bruce Wright,2001,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...
2,0060973129,Decision in Normandy,Carlo D'Este,1991,HarperPerennial,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...
3,0374157065,Flu: The Story of the Great Influenza Pandemic...,Gina Bari Kolata,1999,Farrar Straus Giroux,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...
4,0393045218,The Mummies of Urumchi,E. J. W. Barber,1999,W. W. Norton &amp; Company,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...

In [138]:
users.head()

   User-ID                            Location   Age
0        1                  nyc, new york, usa   NaN
1        2           stockton, california, usa  18.0
2        3     moscow, yukon territory, russia   NaN
3        4           porto, v.n.gaia, portugal  17.0
4        5  farnborough, hants, united kingdom   NaN

The above dataset is used to store user data ( their userid, location and age)

In [139]:
ratings.head()

   User-ID        ISBN  Book-Rating
0   276725  034545104X            0
1   276726  0155061224            5
2   276727  0446520802            0
3   276729  052165615X            3
4   276729  0521795028            6

So above dataset has 3 columns, column 1 is userid(specific id given to the user), column 2 is ISBN number (unique number given to the books) and book rating is the rating given by a specific user to a specific book

In [140]:
print(books.shape)
print(ratings.shape)
print(users.shape)

(271360, 8)
(1149780, 3)
(278858, 3)

In [141]:
books.isnull().sum()

ISBN                   0
Book-Title             0
Book-Author            2
Year-Of-Publication    0
Publisher              2
Image-URL-S            0
Image-URL-M            0
Image-URL-L            3
dtype: int64

In [142]:
users.isnull().sum()

User-ID          0
Location         0
Age         110762
dtype: int64

In [143]:
ratings.isnull().sum()

User-ID        0
ISBN           0
Book-Rating    0
dtype: int64

In [144]:
books.duplicated().sum()

np.int64(0)

In [145]:
ratings.duplicated().sum()

np.int64(0)

In [146]:
users.duplicated().sum()

np.int64(0)

# Popularity Based Recommender System

In [147]:
ratings_with_name = ratings.merge(books,on='ISBN')

In [148]:
num_rating_df = ratings_with_name.groupby('Book-Title').count()['Book-Rating'].reset_index()
num_rating_df.rename(columns={'Book-Rating':'num_ratings'},inplace=True)
num_rating_df

                                               Book-Title  num_ratings
0        A Light in the Storm: The Civil War Diary of ...            4
1                                   Always Have Popsicles            1
2                    Apple Magic (The Collector's series)            1
3        Ask Lily (Young Women of Faith: Lily Series, ...            1
4        Beyond IBM: Leadership Marketing and Finance ...            1
...                                                   ...          ...
241066                                      Ã?Â?lpiraten.            2
241067                     Ã?Â?rger mit Produkt X. Roman.            4
241068                                Ã?Â?sterlich leben.            1
241069                              Ã?Â?stlich der Berge.            3
241070                                  Ã?Â?thique en toc            2

[241071 rows x 2 columns]

In [149]:
avg_rating_df = ratings_with_name.groupby('Book-Title')['Book-Rating'].mean().reset_index()
avg_rating_df.rename(columns={'Book-Rating':'avg_rating'},inplace=True)
avg_rating_df

                                               Book-Title  avg_rating
0        A Light in the Storm: The Civil War Diary of ...    2.250000
1                                   Always Have Popsicles    0.000000
2                    Apple Magic (The Collector's series)    0.000000
3        Ask Lily (Young Women of Faith: Lily Series, ...    8.000000
4        Beyond IBM: Leadership Marketing and Finance ...    0.000000
...                                                   ...         ...
241066                                      Ã?Â?lpiraten.    0.000000
241067                     Ã?Â?rger mit Produkt X. Roman.    5.250000
241068                                Ã?Â?sterlich leben.    7.000000
241069                              Ã?Â?stlich der Berge.    2.666667
241070                                  Ã?Â?thique en toc    4.000000

[241071 rows x 2 columns]

Now the popular df will be given by

In [150]:

popular_df = num_rating_df.merge(avg_rating_df,on='Book-Title')
popular_df

,Book-Title,num_ratings,avg_rating
0,A Light in the Storm: The Civil War Diary of ...,4,2.250000
1,Always Have Popsicles,1,0.000000
2,Apple Magic (The Collector's series),1,0.000000
3,"Ask Lily (Young Women of Faith: Lily Series, ...",1,8.000000
4,Beyond IBM: Leadership Marketing and Finance ...,1,0.000000
...,...,...,...
241066,Ã?Â?lpiraten.,2,0.000000
241067,Ã?Â?rger mit Produkt X. Roman.,4,5.250000
241068,Ã?Â?sterlich leben.,1,7.000000
241069,Ã?Â?stlich der Berge.,3,2.666667
241070,Ã?Â?thique en toc,2,4.000000

In [151]:
popular_df = popular_df[popular_df["num_ratings"]>=250].sort_values("avg_rating",ascending=False)

In [152]:
popular_df

,Book-Title,num_ratings,avg_rating
80434,Harry Potter and the Prisoner of Azkaban (Book 3),428,5.852804
80422,Harry Potter and the Goblet of Fire (Book 4),387,5.824289
80441,Harry Potter and the Sorcerer's Stone (Book 1),278,5.737410
80426,Harry Potter and the Order of the Phoenix (Boo...,347,5.501441
80414,Harry Potter and the Chamber of Secrets (Book 2),556,5.183453
...,...,...,...
227701,Vinegar Hill (Oprah's Book Club (Paperback)),265,2.245283
233635,Whispers,286,2.199301
143377,Presumed Innocent,294,2.139456
94382,Isle of Dogs,288,2.000000
234951,Wild Animus,2502,1.019584

merge in python acts as join in sql

to get the name of book author, image related to it, year of publication and other details, we will join popular_df with book df and our common column will be Book title

In [153]:
popular_df.merge(books,on="Book-Title").drop_duplicates("Book-Title")[["Book-Title","Book-Author","num_ratings","avg_rating"]]

,Book-Title,Book-Author,num_ratings,avg_rating
0,Harry Potter and the Prisoner of Azkaban (Book 3),J. K. Rowling,428,5.852804
3,Harry Potter and the Goblet of Fire (Book 4),J. K. Rowling,387,5.824289
5,Harry Potter and the Sorcerer's Stone (Book 1),J. K. Rowling,278,5.737410
9,Harry Potter and the Order of the Phoenix (Boo...,J. K. Rowling,347,5.501441
13,Harry Potter and the Chamber of Secrets (Book 2),J. K. Rowling,556,5.183453
...,...,...,...,...
716,Vinegar Hill (Oprah's Book Club (Paperback)),A. Manette Ansay,265,2.245283
717,Whispers,BELVA PLAIN,286,2.199301
727,Presumed Innocent,Scott Turow,294,2.139456
733,Isle of Dogs,Patricia Cornwell,288,2.000000
739,Wild Animus,Rich Shapero,2502,1.019584

# Collaborative Filtering Based Recommender System

Here we will also consider, how many people are serious readors and we will consider the feedback of those serious readors to reccomend a book to another user.

Meanwhile we also need to consider which books are popular, how many ratings they are getting

In [154]:
ratings_with_name

,User-ID,ISBN,Book-Rating,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
0,276725,034545104X,0,Flesh Tones: A Novel,M. J. Rose,2002,Ballantine Books,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...
1,276726,0155061224,5,Rites of Passage,Judith Rae,2001,Heinle,http://images.amazon.com/images/P/0155061224.0...,http://images.amazon.com/images/P/0155061224.0...,http://images.amazon.com/images/P/0155061224.0...
2,276727,0446520802,0,The Notebook,Nicholas Sparks,1996,Warner Books,http://images.amazon.com/images/P/0446520802.0...,http://images.amazon.com/images/P/0446520802.0...,http://images.amazon.com/images/P/0446520802.0...
3,276729,052165615X,3,Help!: Level 1,Philip Prowse,1999,Cambridge University Press,http://images.amazon.com/images/P/052165615X.0...,http://images.amazon.com/images/P/052165615X.0...,http://images.amazon.com/images/P/052165615X.0...
4,276729,0521795028,6,The Amsterdam Connection : Level 4 (Cambridge ...,Sue Leather,2001,Cambridge University Press,http://images.amazon.com/images/P/0521795028.0...,http://images.amazon.com/images/P/0521795028.0...,http://images.amazon.com/images/P/0521795028.0...
...,...,...,...,...,...,...,...,...,...,...
1031131,276704,0876044011,0,Edgar Cayce on the Akashic Records: The Book o...,Kevin J. Todeschi,1998,A.R.E. Press (Association of Research &amp; Enlig,http://images.amazon.com/images/P/0876044011.0...,http://images.amazon.com/images/P/0876044011.0...,http://images.amazon.com/images/P/0876044011.0...
1031132,276704,1563526298,9,Get Clark Smart : The Ultimate Guide for the S...,Clark Howard,2000,Longstreet Press,http://images.amazon.com/images/P/1563526298.0...,http://images.amazon.com/images/P/1563526298.0...,http://images.amazon.com/images/P/1563526298.0...
1031133,276706,0679447156,0,Eight Weeks to Optimum Health: A Proven Progra...,Andrew Weil,1997,Alfred A. Knopf,http://images.amazon.com/images/P/0679447156.0...,http://images.amazon.com/images/P/0679447156.0...,http://images.amazon.com/images/P/0679447156.0...
1031134,276709,0515107662,10,The Sherbrooke Bride (Bride Trilogy (Paperback)),Catherine Coulter,1996,Jove Books,http://images.amazon.com/images/P/0515107662.0...,http://images.amazon.com/images/P/0515107662.0...,http://images.amazon.com/images/P/0515107662.0...
1031135,276721,0590442449,10,Fourth Grade Rats,Jerry Spinelli,1996,Scholastic,http://images.amazon.com/images/P/0590442449.0...,http://images.amazon.com/images/P/0590442449.0...,http://images.amazon.com/images/P/0590442449.0...

In [155]:
#Here we are checking the number of users who have given more than 200 ratings
users = ratings_with_name.groupby("User-ID").count()["Book-Rating"] > 200

serious_users = users[users].index

In [158]:
filtered_users = ratings_with_name[ratings_with_name["User-ID"].isin(serious_users)]
filtered_users

,User-ID,ISBN,Book-Rating,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
1150,277427,002542730X,10,Politically Correct Bedtime Stories: Modern Ta...,James Finn Garner,1994,John Wiley &amp; Sons Inc,http://images.amazon.com/images/P/002542730X.0...,http://images.amazon.com/images/P/002542730X.0...,http://images.amazon.com/images/P/002542730X.0...
1151,277427,0026217457,0,Vegetarian Times Complete Cookbook,Lucy Moll,1995,John Wiley &amp; Sons,http://images.amazon.com/images/P/0026217457.0...,http://images.amazon.com/images/P/0026217457.0...,http://images.amazon.com/images/P/0026217457.0...
1152,277427,003008685X,8,Pioneers,James Fenimore Cooper,1974,Thomson Learning,http://images.amazon.com/images/P/003008685X.0...,http://images.amazon.com/images/P/003008685X.0...,http://images.amazon.com/images/P/003008685X.0...
1153,277427,0030615321,0,"Ask for May, Settle for June (A Doonesbury book)",G. B. Trudeau,1982,Henry Holt &amp; Co,http://images.amazon.com/images/P/0030615321.0...,http://images.amazon.com/images/P/0030615321.0...,http://images.amazon.com/images/P/0030615321.0...
1154,277427,0060002050,0,On a Wicked Dawn (Cynster Novels),Stephanie Laurens,2002,Avon Books,http://images.amazon.com/images/P/0060002050.0...,http://images.amazon.com/images/P/0060002050.0...,http://images.amazon.com/images/P/0060002050.0...
...,...,...,...,...,...,...,...,...,...,...
1029357,275970,1931868123,0,There's a Porcupine in My Outhouse: Misadventu...,Mike Tougias,2002,Capital Books (VA),http://images.amazon.com/images/P/1931868123.0...,http://images.amazon.com/images/P/1931868123.0...,http://images.amazon.com/images/P/1931868123.0...
1029358,275970,3411086211,10,Die Biene.,Sybil GrÃ?Â¤fin SchÃ?Â¶nfeldt,1993,"Bibliographisches Institut, Mannheim",http://images.amazon.com/images/P/3411086211.0...,http://images.amazon.com/images/P/3411086211.0...,http://images.amazon.com/images/P/3411086211.0...
1029359,275970,3829021860,0,The Penis Book,Joseph Cohen,1999,Konemann,http://images.amazon.com/images/P/3829021860.0...,http://images.amazon.com/images/P/3829021860.0...,http://images.amazon.com/images/P/3829021860.0...
1029360,275970,4770019572,0,Musashi,Eiji Yoshikawa,1995,Kodansha International (JPN),http://images.amazon.com/images/P/4770019572.0...,http://images.amazon.com/images/P/4770019572.0...,http://images.amazon.com/images/P/4770019572.0...
1029361,275970,9626340762,8,Northanger Abbey (Classic Literature with Clas...,Jane Austen,1996,Naxos Audiobooks Ltd.,http://images.amazon.com/images/P/9626340762.0...,http://images.amazon.com/images/P/9626340762.0...,http://images.amazon.com/images/P/9626340762.0...

So 474007 ratings are given by just these top 200 serious users

In [161]:
famous_books = filtered_users.groupby("Book-Title").count()["Book-Rating"] > 50
famous_books

Book-Title
 A Light in the Storm: The Civil War Diary of Amelia Martin, Fenwick Island, Delaware, 1861 (Dear America)    False
 Always Have Popsicles                                                                                        False
 Apple Magic (The Collector's series)                                                                         False
 Beyond IBM: Leadership Marketing and Finance for the 1990s                                                   False
 Clifford Visita El Hospital (Clifford El Gran Perro Colorado)                                                False
                                                                                                              ...
Ã?Â?ber das Fernsehen.                                                                                        False
Ã?Â?ber die Pflicht zum Ungehorsam gegen den Staat.                                                           False
Ã?Â?lpiraten.                                                                                                 False
Ã?Â?stlich der Berge.                                                                                         False
Ã?Â?thique en toc                                                                                             False
Name: Book-Rating, Length: 155845, dtype: bool

In [162]:
famous_books = famous_books[famous_books].index

In [163]:
famous_books

Index(['1984', '1st to Die: A Novel', '2nd Chance', '4 Blondes',
       'A Bend in the Road', 'A Case of Need',
       'A Child Called \It\": One Child's Courage to Survive"',
       'A Civil Action', 'A Day Late and a Dollar Short', 'A Fine Balance',
       ...
       'Winter Solstice', 'Wish You Well', 'Without Remorse',
       'Wizard and Glass (The Dark Tower, Book 4)', 'Wuthering Heights',
       'Year of Wonders', 'You Belong To Me',
       'Zen and the Art of Motorcycle Maintenance: An Inquiry into Values',
       'Zoya', '\O\" Is for Outlaw"'],
      dtype='object', name='Book-Title', length=679)

In [165]:
final_ratings = filtered_users[filtered_users["Book-Title"].isin(famous_books)]

In [166]:
final_ratings.drop_duplicates()

,User-ID,ISBN,Book-Rating,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
1150,277427,002542730X,10,Politically Correct Bedtime Stories: Modern Ta...,James Finn Garner,1994,John Wiley &amp; Sons Inc,http://images.amazon.com/images/P/002542730X.0...,http://images.amazon.com/images/P/002542730X.0...,http://images.amazon.com/images/P/002542730X.0...
1163,277427,0060930535,0,The Poisonwood Bible: A Novel,Barbara Kingsolver,1999,Perennial,http://images.amazon.com/images/P/0060930535.0...,http://images.amazon.com/images/P/0060930535.0...,http://images.amazon.com/images/P/0060930535.0...
1165,277427,0060934417,0,Bel Canto: A Novel,Ann Patchett,2002,Perennial,http://images.amazon.com/images/P/0060934417.0...,http://images.amazon.com/images/P/0060934417.0...,http://images.amazon.com/images/P/0060934417.0...
1168,277427,0061009059,9,One for the Money (Stephanie Plum Novels (Pape...,Janet Evanovich,1995,HarperTorch,http://images.amazon.com/images/P/0061009059.0...,http://images.amazon.com/images/P/0061009059.0...,http://images.amazon.com/images/P/0061009059.0...
1174,277427,006440188X,0,The Secret Garden,Frances Hodgson Burnett,1998,HarperTrophy,http://images.amazon.com/images/P/006440188X.0...,http://images.amazon.com/images/P/006440188X.0...,http://images.amazon.com/images/P/006440188X.0...
...,...,...,...,...,...,...,...,...,...,...
1029196,275970,1400031354,0,Tears of the Giraffe (No.1 Ladies Detective Ag...,Alexander McCall Smith,2002,Anchor,http://images.amazon.com/images/P/1400031354.0...,http://images.amazon.com/images/P/1400031354.0...,http://images.amazon.com/images/P/1400031354.0...
1029197,275970,1400031362,0,Morality for Beautiful Girls (No.1 Ladies Dete...,Alexander McCall Smith,2002,Anchor,http://images.amazon.com/images/P/1400031362.0...,http://images.amazon.com/images/P/1400031362.0...,http://images.amazon.com/images/P/1400031362.0...
1029270,275970,1573229725,0,Fingersmith,Sarah Waters,2002,Riverhead Books,http://images.amazon.com/images/P/1573229725.0...,http://images.amazon.com/images/P/1573229725.0...,http://images.amazon.com/images/P/1573229725.0...
1029309,275970,1586210661,9,Me Talk Pretty One Day,David Sedaris,2001,Time Warner Audio Major,http://images.amazon.com/images/P/1586210661.0...,http://images.amazon.com/images/P/1586210661.0...,http://images.amazon.com/images/P/1586210661.0...
1029310,275970,1586212230,0,Naked,David Sedaris,2001,Time Warner Audio Major,http://images.amazon.com/images/P/1586212230.0...,http://images.amazon.com/images/P/1586212230.0...,http://images.amazon.com/images/P/1586212230.0...

In [168]:
pt = final_ratings.pivot_table(index="Book-Title",columns="User-ID",values="Book-Rating")

In [169]:
pt

User-ID,254,2276,2766,2977,3363,4017,4385,6251,6323,6543,...,271705,273979,274004,274061,274301,274308,275970,277427,277639,278418
Book-Title,,,,,,,,,,,,,,,,,,,,,
1984,9.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,10.0,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN
1st to Die: A Novel,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2nd Chance,NaN,10.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,...,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,0.0,NaN
4 Blondes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
A Bend in the Road,0.0,NaN,7.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Year of Wonders,NaN,NaN,NaN,7.0,NaN,NaN,NaN,NaN,NaN,0.0,...,NaN,9.0,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN
You Belong To Me,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Zen and the Art of Motorcycle Maintenance: An Inquiry into Values,NaN,NaN,NaN,NaN,0.0,NaN,NaN,0.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN
Zoya,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
"\O\"" Is for Outlaw""",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,8.0,NaN,NaN,NaN,NaN,NaN

In [170]:
pt.fillna(0,inplace=True)

In [171]:
pt

User-ID,254,2276,2766,2977,3363,4017,4385,6251,6323,6543,...,271705,273979,274004,274061,274301,274308,275970,277427,277639,278418
Book-Title,,,,,,,,,,,,,,,,,,,,,
1984,9.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,10.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1st to Die: A Novel,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,9.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2nd Chance,0.0,10.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4 Blondes,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
A Bend in the Road,0.0,0.0,7.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Year of Wonders,0.0,0.0,0.0,7.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,9.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
You Belong To Me,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Zen and the Art of Motorcycle Maintenance: An Inquiry into Values,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Zoya,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
"\O\"" Is for Outlaw""",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,8.0,0.0,0.0,0.0,0.0,0.0

in above pivot table, each book can be seen as a vector in a 679 dimensional space. Now we need to find how these vectors are similar to each other by calculating Euclidien distance between them.

In [174]:
from sklearn.metrics.pairwise import cosine_similarity

In [180]:
similarity_score = cosine_similarity(pt)

Similarity score is signifying the similarity between each book eith each of the book

In [185]:
print(list(enumerate(similarity_score[0])))

[(0, np.float64(0.9999999999999998)), (1, np.float64(0.10255024829874466)), (2, np.float64(0.012208555646509366)), (3, np.float64(0.0)), (4, np.float64(0.053672244225442485)), (5, np.float64(0.027749013024662858)), (6, np.float64(0.08216491130000354)), (7, np.float64(0.13732869060263378)), (8, np.float64(0.03261686350494277)), (9, np.float64(0.03667590746512177)), (10, np.float64(0.02322418425912186)), (11, np.float64(0.06766486753662343)), (12, np.float64(0.020839782065795794)), (13, np.float64(0.09673734976610586)), (14, np.float64(0.0830311169181103)), (15, np.float64(0.1115354275858341)), (16, np.float64(0.05100410510067514)), (17, np.float64(0.025177841632809915)), (18, np.float64(0.11706383185253948)), (19, np.float64(0.0)), (20, np.float64(0.14333792815336935)), (21, np.float64(0.07847534327232125)), (22, np.float64(0.06150451339525138)), (23, np.float64(0.08723968326958673)), (24, np.float64(0.0)), (25, np.float64(0.07009814362931202)), (26, np.float64(0.13658680855472938)), (27, np.float64(0.07600327535501017)), (28, np.float64(0.12167133598776536)), (29, np.float64(0.007680459111722776)), (30, np.float64(0.01473221255132234)), (31, np.float64(0.0)), (32, np.float64(0.07965814289647455)), (33, np.float64(0.04522616573040869)), (34, np.float64(0.01556270914112474)), (35, np.float64(0.09495937740802216)), (36, np.float64(0.018230696811058135)), (37, np.float64(0.026104653172312028)), (38, np.float64(0.07984012108659384)), (39, np.float64(0.11679968613719668)), (40, np.float64(0.056912401804646934)), (41, np.float64(0.08354155383339157)), (42, np.float64(0.08471898090442946)), (43, np.float64(0.08785938150991274)), (44, np.float64(0.05491435163039676)), (45, np.float64(0.054850498513470236)), (46, np.float64(0.2702651417103732)), (47, np.float64(0.09779122591837028)), (48, np.float64(0.060160461842087495)), (49, np.float64(0.08958834926611466)), (50, np.float64(0.06748675491514017)), (51, np.float64(0.0)), (52, np.float64(0.044680983219421905)), (53, np.float64(0.019208718234636258)), (54, np.float64(0.0)), (55, np.float64(0.05629066845910846)), (56, np.float64(0.005579638588454276)), (57, np.float64(0.07877058635507732)), (58, np.float64(0.052194792200893965)), (59, np.float64(0.18908176672188648)), (60, np.float64(0.0)), (61, np.float64(0.012406560213354146)), (62, np.float64(0.029845724311982225)), (63, np.float64(0.04279501979786338)), (64, np.float64(0.12680124740531368)), (65, np.float64(0.16566734565340116)), (66, np.float64(0.0)), (67, np.float64(0.13357242093379193)), (68, np.float64(0.06615478064452682)), (69, np.float64(0.0)), (70, np.float64(0.0)), (71, np.float64(0.0)), (72, np.float64(0.1096807501418389)), (73, np.float64(0.02806606106883051)), (74, np.float64(0.04521795287053612)), (75, np.float64(0.06876130890656589)), (76, np.float64(0.013316271087745269)), (77, np.float64(0.10519138203342883)), (78, np.float64(0.03349456939792139)), (79, np.float64(0.013634576553468258)), (80, np.float64(0.23669374347400993)), (81, np.float64(0.0)), (82, np.float64(0.10397940924207362)), (83, np.float64(0.06167753120046458)), (84, np.float64(0.11661082872914152)), (85, np.float64(0.08331012208964667)), (86, np.float64(0.00850895140653615)), (87, np.float64(0.06715432766232284)), (88, np.float64(0.0)), (89, np.float64(0.15850821182810643)), (90, np.float64(0.03280520241000348)), (91, np.float64(0.010689154840164533)), (92, np.float64(0.025797824097510556)), (93, np.float64(0.02114858980511902)), (94, np.float64(0.02687778911799567)), (95, np.float64(0.02175821065382328)), (96, np.float64(0.0)), (97, np.float64(0.016016629607635186)), (98, np.float64(0.04768602689229997)), (99, np.float64(0.058191840680734276)), (100, np.float64(0.06510721558252526)), (101, np.float64(0.0)), (102, np.float64(0.047670497142785574)), (103, np.float64(0.05273164983675109)), (104, np.float64(0.02810009706063171)), (105, np.float64(0.06524573363186935)), (106, np.float64(0.021163446843373374)), (107, np.float64(0.02097867986921867)), (108, np.float64(0.07422249010392888)), (109, np.float64(0.017527779718968118)), (110, np.float64(0.03734566872286401)), (111, np.float64(0.01579666260459111)), (112, np.float64(0.1103944810687539)), (113, np.float64(0.165272766123669)), (114, np.float64(0.15514318804365945)), (115, np.float64(0.06237453600241552)), (116, np.float64(0.08139488796880032)), (117, np.float64(0.056554138733275305)), (118, np.float64(0.07458202717929566)), (119, np.float64(0.03771888280719047)), (120, np.float64(0.059363300295016304)), (121, np.float64(0.02955369248311012)), (122, np.float64(0.03355602562283)), (123, np.float64(0.04734092759216691)), (124, np.float64(0.010066425112509755)), (125, np.float64(0.016719816747289874)), (126, np.float64(0.07258934796997447)), (127, np.float64(0.0)), (128, np.float64(0.0)), (129, np.float64(0.0)), (130, np.float64(0.02428501142412964)), (131, np.float64(0.030678189040978528)), (132, np.float64(0.09974980034668827)), (133, np.float64(0.0)), (134, np.float64(0.016901518597837405)), (135, np.float64(0.024108621631248803)), (136, np.float64(0.028108399645259814)), (137, np.float64(0.0)), (138, np.float64(0.0)), (139, np.float64(0.0181287703514146)), (140, np.float64(0.028808272598853126)), (141, np.float64(0.05995157134958024)), (142, np.float64(0.021276714965680187)), (143, np.float64(0.10341190148072846)), (144, np.float64(0.027667475691473428)), (145, np.float64(0.10684794535545848)), (146, np.float64(0.09898722239993361)), (147, np.float64(0.14145186155692357)), (148, np.float64(0.05007429159938883)), (149, np.float64(0.09428288870384942)), (150, np.float64(0.014112489355409683)), (151, np.float64(0.07835976130061303)), (152, np.float64(0.00882242400686552)), (153, np.float64(0.04515898041752436)), (154, np.float64(0.0)), (155, np.float64(0.012814117802391826)), (156, np.float64(0.04003333547158616)), (157, np.float64(0.07477661367406771)), (158, np.float64(0.012179056920074677)), (159, np.float64(0.018873932015163516)), (160, np.float64(0.026674838717939867)), (161, np.float64(0.01432863977616057)), (162, np.float64(0.14702846562277322)), (163, np.float64(0.06087281632872059)), (164, np.float64(0.025783211586063344)), (165, np.float64(0.027418756526771074)), (166, np.float64(0.0)), (167, np.float64(0.14909595195082756)), (168, np.float64(0.05606788035530558)), (169, np.float64(0.0)), (170, np.float64(0.03199916313406436)), (171, np.float64(0.03643816906953526)), (172, np.float64(0.0)), (173, np.float64(0.01962921144060071)), (174, np.float64(0.22222254415660225)), (175, np.float64(0.015158449197584845)), (176, np.float64(0.09673267751838878)), (177, np.float64(0.02190023295408395)), (178, np.float64(0.020135489410098205)), (179, np.float64(0.05400331245399732)), (180, np.float64(0.07262017448772083)), (181, np.float64(0.011116365315772406)), (182, np.float64(0.036498718026030004)), (183, np.float64(0.05994663767295999)), (184, np.float64(0.0)), (185, np.float64(0.14691166711955864)), (186, np.float64(0.020860053643757807)), (187, np.float64(0.1035963528100001)), (188, np.float64(0.09794374510256892)), (189, np.float64(0.06609996896203728)), (190, np.float64(0.12871083086643306)), (191, np.float64(0.08992738703666601)), (192, np.float64(0.011474570339750256)), (193, np.float64(0.024601653277066596)), (194, np.float64(0.0)), (195, np.float64(0.18049207281616433)), (196, np.float64(0.05141892092902459)), (197, np.float64(0.047717402129725514)), (198, np.float64(0.10849696385128585)), (199, np.float64(0.1327813903167589)), (200, np.float64(0.059152881703632795)), (201, np.float64(0.053729841666378134)), (202, np.float64(0.034785003361519164)), (203, np.float64(0.0)), (204, np.float64(0.09203038690315052)), (205, np.float64(0.06388401351716998)), (206, np.float64(0.04773328410790857)), (207, np.float64(0.15570975499937129)), (208, np.float64(0.08420691059370962)), (209, np.float64(0.12338216998991305)), (210, np.float64(0.08784690368235953)), (211, np.float64(0.08205944603394638)), (212, np.float64(0.024337026385897676)), (213, np.float64(0.00272862336930817)), (214, np.float64(0.0)), (215, np.float64(0.03671505063990275)), (216, np.float64(0.1528098402276361)), (217, np.float64(0.03709430441334803)), (218, np.float64(0.07458136399603107)), (219, np.float64(0.09746696979819942)), (220, np.float64(0.05416091103251691)), (221, np.float64(0.10266993316420167)), (222, np.float64(0.0757441443938586)), (223, np.float64(0.06426525769208898)), (224, np.float64(0.03601739518550193)), (225, np.float64(0.01559751952620105)), (226, np.float64(0.02033558874805688)), (227, np.float64(0.024635927968282654)), (228, np.float64(0.0)), (229, np.float64(0.021353685011361416)), (230, np.float64(0.019033695446023926)), (231, np.float64(0.06806264765162154)), (232, np.float64(0.020321161226731627)), (233, np.float64(0.11784705785247843)), (234, np.float64(0.07839488163675291)), (235, np.float64(0.08422557655984436)), (236, np.float64(0.0)), (237, np.float64(0.02040796206066411)), (238, np.float64(0.0)), (239, np.float64(0.046982457315643385)), (240, np.float64(0.08294512991462386)), (241, np.float64(0.13974513728492968)), (242, np.float64(0.012345246102533871)), (243, np.float64(0.1351060763800879)), (244, np.float64(0.07423488726781508)), (245, np.float64(0.1184188929166314)), (246, np.float64(0.049300912125160704)), (247, np.float64(0.016216682151444957)), (248, np.float64(0.026330228561191004)), (249, np.float64(0.04815971759587031)), (250, np.float64(0.019598256153707194)), (251, np.float64(0.10174252819190155)), (252, np.float64(0.13257638388225185)), (253, np.float64(0.0)), (254, np.float64(0.055102704646119355)), (255, np.float64(0.018611497829688243)), (256, np.float64(0.0)), (257, np.float64(0.04504597870526374)), (258, np.float64(0.03482458685305275)), (259, np.float64(0.1650329228149958)), (260, np.float64(0.08466191294337998)), (261, np.float64(0.06795352889900172)), (262, np.float64(0.029876534978291205)), (263, np.float64(0.0)), (264, np.float64(0.0)), (265, np.float64(0.08781992709390865)), (266, np.float64(0.07885279086963545)), (267, np.float64(0.04799058127298857)), (268, np.float64(0.014679640011206505)), (269, np.float64(0.021238372796229556)), (270, np.float64(0.04549923467689111)), (271, np.float64(0.08673968616705958)), (272, np.float64(0.00885998445194921)), (273, np.float64(0.028806369616477166)), (274, np.float64(0.020221447157344582)), (275, np.float64(0.024141217209915328)), (276, np.float64(0.12548312467838352)), (277, np.float64(0.0)), (278, np.float64(0.02482518222135733)), (279, np.float64(0.06520605980064662)), (280, np.float64(0.0)), (281, np.float64(0.06069830203664196)), (282, np.float64(0.13974104783917973)), (283, np.float64(0.019788442258843547)), (284, np.float64(0.012608239194211564)), (285, np.float64(0.08608600626732467)), (286, np.float64(0.04433882752568145)), (287, np.float64(0.029430847399312027)), (288, np.float64(0.022424955017243866)), (289, np.float64(0.06541867556977009)), (290, np.float64(0.07866868132289853)), (291, np.float64(0.1428139852200272)), (292, np.float64(0.11979305199464946)), (293, np.float64(0.01858409288796079)), (294, np.float64(0.13445376799866068)), (295, np.float64(0.09790644477767069)), (296, np.float64(0.0)), (297, np.float64(0.17415730924332484)), (298, np.float64(0.07437756212042423)), (299, np.float64(0.0)), (300, np.float64(0.1238906533021012)), (301, np.float64(0.010423913217045038)), (302, np.float64(0.025808491020821493)), (303, np.float64(0.0)), (304, np.float64(0.08951389572154368)), (305, np.float64(0.04005551020725377)), (306, np.float64(0.19182230688281934)), (307, np.float64(0.02267512161790004)), (308, np.float64(0.017303468493582226)), (309, np.float64(0.03054044240047009)), (310, np.float64(0.0700882246357741)), (311, np.float64(0.10084626149563478)), (312, np.float64(0.10467615354986062)), (313, np.float64(0.016834621675675482)), (314, np.float64(0.12468283384023092)), (315, np.float64(0.10266459423639845)), (316, np.float64(0.035498355256648746)), (317, np.float64(0.026674838717939867)), (318, np.float64(0.07652764821891074)), (319, np.float64(0.08474055728984814)), (320, np.float64(0.018319772326554337)), (321, np.float64(0.021774817728178283)), (322, np.float64(0.15293362041446346)), (323, np.float64(0.0)), (324, np.float64(0.0)), (325, np.float64(0.010632508151830204)), (326, np.float64(0.021530886296301118)), (327, np.float64(0.02946442510264468)), (328, np.float64(0.0)), (329, np.float64(0.020767833514212724)), (330, np.float64(0.011948245768325256)), (331, np.float64(0.009536746594659161)), (332, np.float64(0.20675540390453995)), (333, np.float64(0.015542921836058245)), (334, np.float64(0.03902659506471766)), (335, np.float64(0.06681045925540752)), (336, np.float64(0.09014973218560088)), (337, np.float64(0.05914734917065386)), (338, np.float64(0.06206857320564754)), (339, np.float64(0.0)), (340, np.float64(0.020059585724360268)), (341, np.float64(0.07843565693314272)), (342, np.float64(0.16337845332530374)), (343, np.float64(0.07161075491687474)), (344, np.float64(0.0)), (345, np.float64(0.1459525808785892)), (346, np.float64(0.029397384230560795)), (347, np.float64(0.047796293241950796)), (348, np.float64(0.018072383204619496)), (349, np.float64(0.11362722122094872)), (350, np.float64(0.09791273187403501)), (351, np.float64(0.07999692625971765)), (352, np.float64(0.0891233745026412)), (353, np.float64(0.10941777035919222)), (354, np.float64(0.0)), (355, np.float64(0.02115842407200956)), (356, np.float64(0.060039300152930415)), (357, np.float64(0.017971540540139944)), (358, np.float64(0.05755407693373189)), (359, np.float64(0.021668631362692693)), (360, np.float64(0.09754449459555777)), (361, np.float64(0.13107651944057502)), (362, np.float64(0.0)), (363, np.float64(0.06829903941402894)), (364, np.float64(0.09132921952528268)), (365, np.float64(0.0)), (366, np.float64(0.02781406274224919)), (367, np.float64(0.015333681815045101)), (368, np.float64(0.06113178628791212)), (369, np.float64(0.017572862308732076)), (370, np.float64(0.018015801292409934)), (371, np.float64(0.1178980615083171)), (372, np.float64(0.06468143253238315)), (373, np.float64(0.1390419059870689)), (374, np.float64(0.0)), (375, np.float64(0.06671644037106779)), (376, np.float64(0.0)), (377, np.float64(0.0)), (378, np.float64(0.057620863815487075)), (379, np.float64(0.02266096293926825)), (380, np.float64(0.008448763927099017)), (381, np.float64(0.02297481006625077)), (382, np.float64(0.07136276113078666)), (383, np.float64(0.1530551446766823)), (384, np.float64(0.06039873575147915)), (385, np.float64(0.0)), (386, np.float64(0.08996912406728536)), (387, np.float64(0.015459465622161536)), (388, np.float64(0.10135299399598713)), (389, np.float64(0.0)), (390, np.float64(0.016763442237401817)), (391, np.float64(0.0)), (392, np.float64(0.05021880312673623)), (393, np.float64(0.16041182196659062)), (394, np.float64(0.0)), (395, np.float64(0.1343973311768824)), (396, np.float64(0.12508513698245888)), (397, np.float64(0.02329035016031528)), (398, np.float64(0.019872703940133213)), (399, np.float64(0.011056735115042383)), (400, np.float64(0.025480338679592467)), (401, np.float64(0.0089604367821904)), (402, np.float64(0.0824612198578452)), (403, np.float64(0.01902896010686717)), (404, np.float64(0.07025002832914887)), (405, np.float64(0.021636698437203145)), (406, np.float64(0.12822981990037824)), (407, np.float64(0.0999877199669616)), (408, np.float64(0.0635519690782283)), (409, np.float64(0.028830240654024085)), (410, np.float64(0.04335826491498011)), (411, np.float64(0.04706590154362337)), (412, np.float64(0.0522373263993224)), (413, np.float64(0.08982750671022352)), (414, np.float64(0.00875634332679306)), (415, np.float64(0.09923541776574221)), (416, np.float64(0.10228551050235933)), (417, np.float64(0.0)), (418, np.float64(0.12307492189941618)), (419, np.float64(0.01758928833928951)), (420, np.float64(0.020281245334279798)), (421, np.float64(0.1033826953037451)), (422, np.float64(0.130281708532021)), (423, np.float64(0.08988894455657523)), (424, np.float64(0.09005001295005992)), (425, np.float64(0.05332049434044375)), (426, np.float64(0.08033435626539932)), (427, np.float64(0.045977952103493924)), (428, np.float64(0.061398875647666676)), (429, np.float64(0.023049037833599993)), (430, np.float64(0.06523041320455897)), (431, np.float64(0.01915362558614925)), (432, np.float64(0.0)), (433, np.float64(0.04542765998492866)), (434, np.float64(0.0)), (435, np.float64(0.0)), (436, np.float64(0.05261953990010256)), (437, np.float64(0.01317087876205714)), (438, np.float64(0.0)), (439, np.float64(0.0)), (440, np.float64(0.048593102089385304)), (441, np.float64(0.07348190409223959)), (442, np.float64(0.10354480865656568)), (443, np.float64(0.0171880657878069)), (444, np.float64(0.09919937023309428)), (445, np.float64(0.08091989315700655)), (446, np.float64(0.0035883533320389396)), (447, np.float64(0.11122764671322921)), (448, np.float64(0.051434806536338154)), (449, np.float64(0.05666140304625101)), (450, np.float64(0.0)), (451, np.float64(0.060877194204984726)), (452, np.float64(0.10800615252570414)), (453, np.float64(0.0)), (454, np.float64(0.0755468596127809)), (455, np.float64(0.0)), (456, np.float64(0.13644383961641227)), (457, np.float64(0.04796762686649386)), (458, np.float64(0.16104067376144765)), (459, np.float64(0.017598641856748937)), (460, np.float64(0.05438295377092604)), (461, np.float64(0.0)), (462, np.float64(0.08100800937525751)), (463, np.float64(0.13090710604063543)), (464, np.float64(0.00581843892000093)), (465, np.float64(0.07150547342980032)), (466, np.float64(0.05428487095514969)), (467, np.float64(0.06143184266443724)), (468, np.float64(0.051616531477964966)), (469, np.float64(0.19511819825564608)), (470, np.float64(0.1149487959814155)), (471, np.float64(0.06513046875777172)), (472, np.float64(0.06401961292305569)), (473, np.float64(0.0)), (474, np.float64(0.0)), (475, np.float64(0.10853661984252007)), (476, np.float64(0.11400426236261282)), (477, np.float64(0.046392498261486066)), (478, np.float64(0.018252769789423258)), (479, np.float64(0.0)), (480, np.float64(0.011952011165403655)), (481, np.float64(0.21057743765309012)), (482, np.float64(0.058097069301565475)), (483, np.float64(0.043491562429456586)), (484, np.float64(0.02646255704581015)), (485, np.float64(0.07276403383736725)), (486, np.float64(0.05264856975654457)), (487, np.float64(0.07242165076731459)), (488, np.float64(0.06790897506872169)), (489, np.float64(0.016265641643564675)), (490, np.float64(0.024318094429406693)), (491, np.float64(0.020935646634428463)), (492, np.float64(0.13617057407600314)), (493, np.float64(0.11784149206441577)), (494, np.float64(0.08588206473402643)), (495, np.float64(0.0928435169211848)), (496, np.float64(0.11277296885857815)), (497, np.float64(0.06868983304237651)), (498, np.float64(0.08200947294838494)), (499, np.float64(0.13369059478865902)), (500, np.float64(0.0)), (501, np.float64(0.19972624710300058)), (502, np.float64(0.0228620664348094)), (503, np.float64(0.08062879942666365)), (504, np.float64(0.0)), (505, np.float64(0.057560148077814344)), (506, np.float64(0.06738056011305654)), (507, np.float64(0.19656287691544358)), (508, np.float64(0.06306425554305625)), (509, np.float64(0.03499381360818396)), (510, np.float64(0.06123118935155921)), (511, np.float64(0.021801683645525486)), (512, np.float64(0.023175154774464087)), (513, np.float64(0.06476148889541151)), (514, np.float64(0.07052240553428667)), (515, np.float64(0.08280451731096075)), (516, np.float64(0.1700871998622835)), (517, np.float64(0.07213921021695388)), (518, np.float64(0.011722012964226876)), (519, np.float64(0.08541217689607684)), (520, np.float64(0.17990898085771034)), (521, np.float64(0.08007284499901246)), (522, np.float64(0.017396246144706713)), (523, np.float64(0.1672877700938274)), (524, np.float64(0.2639619371123497)), (525, np.float64(0.18408910419891056)), (526, np.float64(0.05600272988869)), (527, np.float64(0.04133585716291763)), (528, np.float64(0.0691101496608291))

In [187]:
def recommend(book_name):
    #fetching the index of the book
    index = np.where(pt.index==book_name)[0][0]
    similar_items = sorted(list(enumerate(similarity_score[index])),key=lambda x:x[1], reverse=True)[1:6]

    suggestions = []
    for i in similar_items:
        print(pt.index[i[0]])
        # suggestions.append(pt.index[i[0]])

    # return suggestions

In [188]:
recommend("Message in a Bottle")

Nights in Rodanthe
The Mulberry Tree
A Walk to Remember
River's End
Nightmares &amp; Dreamscapes

In [189]:
recommend("1984")

Animal Farm
The Handmaid's Tale
Brave New World
The Vampire Lestat (Vampire Chronicles, Book II)
The Hours : A Novel